#ifndef __HSR_ENUM_H__
#define __HSR_ENUM_H__

// HSR layer id
typedef enum
{
	LAYER_PIPE_SIN	= 0,LAYER_PIPE_SIN_HID		= 0,
	LAYER_PIPE_DOU	= 1,LAYER_PIPE_DOU_HID		= 1,
	LAYER_PIPE_CEN	= 2,
	LAYER_PIPE_OTHER= 3,LAYER_PIPE_OTHER_HID	= 3,
	LAYER_PIPE_MARK	= 4,
	LAYER_ELBOW_SIN	= 5,LAYER_ELBOW_SIN_HID		= 5,
	LAYER_ELBOW_DOU	= 6,LAYER_ELBOW_DOU_HID		= 6,
	LAYER_ELBOW_CEN	= 7,
	LAYER_ELBOW_CRS	= 8,
	LAYER_ELBOW_WELD_MARK_LINE  = 9,
	LAYER_ELBOW_WELD_MARK_CIRCLE= 10,
	LAYER_ELBOW_CIRCLE_MARK		= 11,
	LAYER_TEE_SIN	= 12,LAYER_TEE_SIN_HID		= 12,
	LAYER_TEE_DOU	= 13,LAYER_TEE_DOU_HID		= 13,
	LAYER_TEE_CEN	= 14,
	LAYER_OTHER		= 15,LAYER_OTHER_HID		= 15,
	LAYER_EQUI		= 16,LAYER_EQUI_HID			= 16,
	LAYER_EQUI_CEN	= 17,
	LAYER_STRU		= 18,LAYER_STRU_HID			= 18,
	LAYER_STRU_CEN	= 19,
	LAYER_CABLE		= 20,LAYER_CABLE_HID		= 20,
	LAYER_INSTRUMENT= 21,LAYER_INSTRUMENT_HID	= 21,
	LAYER_VIEW		= 22,
	LAYER_DIMENSION	= 23,
	LAYER_ANNOTATION= 24,
	LAYER_BORDER	= 25,
	LAYER_PIPE		= 30,
	LAYER_NONE		= 31
}HSR_LAYER_E;

#endif