//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartDraw.rc
//
#define IDC_BUTTON_COPY_VIEW            3
#define IDC_BUTTON_ADD_REVISION_DATA    3
#define IDC_BUTTON_IMPORT               3
#define IDC_BUTTON_NEW_FILTER           3
#define IDC_BUTTON_REMOVE_VIEW          4
#define IDC_BUTTON_APPLY                4
#define IDOK3                           4
#define IDC_BUTTON_EXPORT               4
#define IDC_BUTTON_DELETE_FILTER        4
#define IDC_BUTTON_FILTER_UP            5
#define IDC_BUTTON_DELETE_FILTER_DOWN   6
#define IDC_BUTTON_FILTER_DOWN          6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_DRA                         101
#define ID_GENERATION_HLR               102
#define ID_GENERATION_ANNOTATION        103
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define IDS_STATUSBAR_PANE1             120
#define IDS_STATUSBAR_PANE2             121
#define IDS_STATUSBAR_PANE3             122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SMARTDRAWTYPE               130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_DELETE_PROPERTIES            153
#define ID_EXPAND_ALL                   154
#define IDS_PROJECT_EXPLORER            155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDR_POPUP_PROJECT               174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_MANUAL               262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_DRAWING_TAB                 300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_LOGIN                       310
#define IDI_OK                          311
#define IDI_CANCEL                      312
#define IDD_NEW_PROJECT                 313
#define IDR_POPUP_DRA                   314
#define IDD_ADRAW_PROPERTYPAGE          315
#define IDR_POPUP_DRA1                  315
#define IDR_POPUP_VIEW                  315
#define IDI_ROOT                        316
#define IDI_SETTING                     317
#define IDI_VIEW                        318
#define IDI_DRA                         319
#define IDD_DRA                         320
#define IDD_DRA_VIEW                    321
#define IDI_MSTNJ                       322
#define IDB_BOX                         323
#define IDB_MULTI_BOXES                 324
#define IDD_AREA_OPTION                 325
#define IDB_AREA_OPTION                 327
#define IDD_ANNOTATION                  328
#define IDD_PROPERTY_SHEET              329
#define IDD_BORDER_PAGE                 330
#define IDD_DIMENSION_PAGE              331
#define IDD_WORK_STATUS                 332
#define IDB_PROJECT                     333
#define IDI_NEW                         337
#define IDI_DELETE                      338
#define IDI_ICON1                       339
#define IDI_TEXT_STYLE                  339
#define IDD_LINE_NO_PAGE                340
#define IDD_INSTRUMENT_PAGE             341
#define IDD_SUPPORT_PAGE                342
#define IDD_NOZZLE_PAGE                 343
#define IDD_REDUCER_PAGE                344
#define IDD_EQUIPMENT_PAGE              345
#define IDD_STRUCTURE_PAGE              346
#define IDD_VALVE_PAGE                  347
#define IDD_OTHER_PAGE                  348
#define IDD_VERTICAL_LINE_HATCHING_PAGE 348
#define IDD_GENERATION_PAGE             349
#define IDD_INSIDE_VIEW_LINE_NO_PAGE    350
#define IDD_OUTSIDE_VIEW_LINE_NO_PAGE   351
#define IDI_EQUIPMENT                   352
#define IDI_NOZZLE                      353
#define IDI_REDUCER                     354
#define IDI_INSTRUMENT                  356
#define IDI_TREE                        357
#define IDI_STRUCTURE                   358
#define IDI_LINE_NO                     359
#define IDI_INSIDE_VIEW                 360
#define IDI_OUTSIDE_VIEW                362
#define IDI_DIMENSION                   363
#define IDI_AREA                        364
#define IDI_BORDER                      365
#define IDI_PROJECT                     366
#define IDI_CABLE_TRAY                  368
#define IDD_FLOW_SLOPE_MARK_PAGE        368
#define IDI_OTHER                       369
#define IDI_SPECIAL_ITEM                370
#define IDB_BITMAP1                     371
#define IDB_AUTOCAD                     371
#define IDI_GENERATION                  372
#define IDI_HATCHING                    375
#define IDI_MARK                        376
#define IDI_ICON3                       377
#define IDI_SUPPORT                     377
#define IDI_REVISION_CHART              378
#define IDI_NOZZLE_CHART                379
#define IDI_TITLE_BLOCK                 380
#define IDI_GRID_NO                     381
#define IDI_KEY_PLAN                    382
#define IDI_FOLDER                      383
#define IDI_DATABASE                    384
#define IDD_NEW_DRA_FILE                385
#define IDI_VIEW_BLUE                   386
#define IDD_GENERATE_DRA_FROM_DRAWING   387
#define IDB_STRUCTURE                   388
#define IDD_TITLE_BLOCK_PAGE            392
#define IDD_GRID_NO_PAGE                393
#define IDD_KEY_PLAN_HATCHING_PAGE      394
#define IDB_SUPPORT                     395
#define IDD_REVISION_CHART_PAGE         395
#define IDB_EQUIPMENT                   396
#define IDD_NOZZLE_CHART_PAGE           396
#define IDR_POPUP_BORDER                396
#define IDR_POPUP_DRA2                  397
#define IDR_POPUP_SETTING               397
#define IDB_DIMENSION_OPTION            398
#define IDB_LINE_NO_INSIDE_VIEW         400
#define IDD_LINE_NO_LABEL_FORMAT        401
#define IDD_PROJECT_SETTING             404
#define IDI_MOUSE_PICK                  404
#define IDI_ADD                         405
#define IDB_PNG1                        406
#define IDD_FOLDER_SETTING_PAGE         407
#define IDD_DATABASE_SETTING_PAGE       408
#define IDB_DISTANCE                    408
#define IDB_CABLE_TRAY                  409
#define IDB_MSTN                        410
#define IDD_PLATFORM_HATCHING_PAGE      412
#define IDD_EQUIPMENT_HATCHING_PAGE     414
#define IDD_SPECIAL_ITEM_PAGE           415
#define IDI_PLUGIN                      416
#define IDI_EQP_HATCHING                418
#define IDI_PF_HATCHING                 420
#define IDD_REVISION_MANAGER            426
#define IDD_HLR_PAGE                    427
#define IDI_HLR                         427
#define IDD_OUTSIDE_EQUIPMENT_PAGE      428
#define IDD_PROGRESS_ANIMATION          429
#define IDD_VIEW_ANNOA_OPTION_PAGE      430
#define IDR_TOOLBAR1                    431
#define IDB_BITMAP2                     434
#define IDB_DEMO                        434
#define IDI_RESET_ACTIVATE_CODE         436
#define IDI_ICON2                       437
#define IDI_OPEN                        437
#define IDB_LOADING_AUTOCAD             438
#define IDR_GIF2                        441
#define IDI_ICON4                       444
#define IDI_AUTOCAD                     444
#define IDD_INSERT_REV_NO               446
#define IDD_PIPE_DIA_EDIT               447
#define IDD_EDIT_TITLE_BLOCK_DATA       448
#define IDI_ICON5                       449
#define IDI_SHORTCUT_OVERLAY            449
#define IDI_VALVE                       450
#define IDI_FILTER                      451
#define IDI_ERROR_OVERLAY               452
#define IDD_ANNO_FILTER                 453
#define IDI_DOWN                        454
#define IDI_UP                          455
#define IDI_REFRESH                     456
#define IDD_DIALOG1                     457
#define IDD_FILL_MATCHLINE_DATA         457
#define IDB_MATCH_LINE_DATA             458
#define IDC_EDIT1                       1000
#define IDC_EDIT_PROJECT_NAME           1000
#define IDC_EDIT_MINX                   1000
#define IDC_EDIT_VIEW_NAME              1000
#define IDC_EDIT_TOP_RANGE              1000
#define IDC_EDIT_CENTER                 1000
#define IDC_EDIT_MATCHLINE_DRAWING_PREFIX 1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_PROJECT_DESC           1001
#define IDC_EDIT_MINY                   1001
#define IDC_EDIT_BOTTOM_RANGE           1001
#define IDC_EDIT_BOP                    1001
#define IDC_EDIT_NO_MATCHLINE_DRAWING   1001
#define IDC_EDIT_MINZ                   1002
#define IDC_EDIT_LEFT_RANGE             1002
#define IDC_EDIT3                       1002
#define IDC_EDIT_TOP                    1002
#define IDC_COMBO_SETTING               1003
#define IDC_EDIT_MAXX                   1003
#define IDC_EDIT_RIGHT_RANGE            1003
#define IDC_EDIT4                       1003
#define IDC_EDIT_EXT_LINE_OFFSET        1003
#define IDC_EDIT_WP                     1003
#define IDC_COMBO_DIRECTION             1004
#define IDC_EDIT5                       1004
#define IDC_EDIT_ARROW_SIZE             1004
#define IDC_EDIT6                       1004
#define IDC_EDIT_DESIGN_DATABASE_NAME   1004
#define IDC_EDIT_KEYPLAN_HATCHING_TEXT_POS_X 1004
#define IDC_EDIT_MAXY                   1005
#define IDC_EDIT7                       1005
#define IDC_EDIT_ARROW_SIZE2            1005
#define IDC_EDIT_KEYPLAN_HATCHING_TEXT_POS_Y 1005
#define IDC_EDIT_MAXZ                   1006
#define IDC_EDIT8                       1006
#define IDC_EDIT_DESIGN_PASSWORD        1006
#define IDC_COMBO_SCALE                 1007
#define IDC_EDIT9                       1007
#define IDC_EDIT_DESIGN_SERVER          1007
#define IDC_COMBO_ANGLE                 1008
#define IDC_LIST_REFERENCE              1009
#define IDC_EDIT_VIEW_ORIGIN_X          1010
#define IDC_COMBO_PROJECT               1011
#define IDC_EDIT_MATCH_LINE_DATA_UP     1011
#define IDC_EDIT_MATCH_LINE_DATA_DOWN   1012
#define IDC_EDIT_MATCH_LINE_DATA_EAST   1013
#define IDC_EDIT_MATCH_LINE_DATA_WEST   1014
#define IDC_EDIT_MATCH_LINE_DATA_SOUTH  1015
#define IDC_EDIT_MATCH_LINE_DATA_NORTH  1016
#define IDC_EDIT_ID                     1017
#define IDC_EDIT_VIEW_INFO              1017
#define IDC_EDIT_PASSWORD               1018
#define IDC_STATIC_FILE_TAB             1018
#define IDC_EDIT_VIEW_ORIGIN_Y          1019
#define IDC_BUTTON_PICK_VIEW_ORIGIN     1020
#define IDC_BUTTON_PICK_FIRST_POINT     1021
#define IDC_BUTTON_PICK_SECOND_POINT    1022
#define IDC_BUTTON_ADD_REFERENCE        1023
#define IDC_BUTTON_REMOVE_REFERENCE     1024
#define IDC_BUTTON_GET_VOLUME_FROM_ALL_REFERENCE 1025
#define IDC_TREE_PAGE                   1026
#define IDC_STATIC_PAGE                 1027
#define IDC_SPIN_TOP_RANGE              1029
#define IDC_SPIN_BOTTOM_RANGE           1030
#define IDC_TEXT_STYLE_COMBO            1030
#define IDC_SPIN_LEFT_RANGE             1031
#define IDC_SPIN_RIGHT_RANGE            1032
#define IDC_STATIC_ITEMS                1034
#define IDC_RADIO_LINE_NO_SIZE_ALL      1035
#define IDC_STATIC_ITEMS2               1035
#define IDC_STATIC_GENERATE_ITEMS       1035
#define IDC_RADIO_LINE_NO_OVER_SIZE     1036
#define IDC_STATIC_ITEMS3               1036
#define IDC_STATIC_LOCATION_ORDER       1036
#define IDC_COMBO_LINE_NO_OVER_SIZE     1037
#define IDC_EDIT_FOLDER                 1038
#define IDC_LINE_NO_SIZE_ALL2           1038
#define IDC_LINE_NO_SIZE_ALL3           1039
#define IDC_BUTTON_SET_SIZE_BY_SPEC     1040
#define IDC_COMBO_OUTPUT_FORMAT         1041
#define IDC_RADIO_LINE_NO_DIM_SIZE_ALL  1041
#define IDC_COMBO_DRAWING_TYPE          1042
#define IDC_COMBO1                      1042
#define IDC_COMBO_ELEV_TYPE             1042
#define IDC_COMBO_ID                    1042
#define IDC_COMBO_FILTER                1042
#define IDC_RADIO_LINE_NO_DIM_OVER_SIZE 1042
#define IDC_COMBO_TAG_RANGE             1042
#define IDC_COMBO_VIEW_COORD_DISPLAY_STYLE 1042
#define IDC_COMBO_REV_NO                1042
#define IDC_TREE_VIEW                   1043
#define IDC_RADIO1                      1043
#define IDC_COMBO_PRECISION             1043
#define IDC_COMBO_GREATER_EQUAL         1043
#define IDC_COMBO_LINE_NO_OVER_SIZE2    1043
#define IDC_COMBO_LINE_NO_DIM_OVER_SIZE 1043
#define IDC_COMBO_TOP_ALIGNMENT_TYPE    1043
#define IDC_COMBO_VIEW_INFO_ALIGNMENT   1043
#define IDC_BUTTON_SAVE_VIEW            1044
#define IDC_RADIO2                      1044
#define IDC_COMBO_BOTTOM_ALIGNMENT_TYPE 1044
#define IDC_COMBO_MATCHLINE_DATA_ALIGNMENT 1044
#define IDC_LIST_PDS_DRAWING            1045
#define IDC_RADIO3                      1045
#define IDC_RADIO_DEPEND_ON_AREA        1045
#define IDC_COMBO_LEFT_ALIGNMENT_TYPE   1045
#define IDC_RADIO4                      1046
#define IDC_COMBO_RIGHT_ALIGNMENT_TYPE  1046
#define IDC_EDIT_DRAWING_FILE_FOLDER    1047
#define IDC_RADIO5                      1047
#define IDC_COMBO_ELEV_TEXT_STYLE       1047
#define IDC_BUTTON_TOGGLE_SELECTION     1048
#define IDC_RADIO6                      1048
#define IDC_COMBO_COORD_TEXT_STYLE      1048
#define IDC_RADIO_CENTER                1048
#define IDC_RADIO_DISPLAY_STYLE2        1048
#define IDC_EDIT_PROJECT_UOR            1049
#define IDC_RADIO_BOP                   1049
#define IDC_RADIO_YAXIS_NUMERIC         1049
#define IDC_RADIO_DISPLAY_STYLE3        1049
#define IDC_COMBO_VIEW_INFO_TEXT_STYLE  1049
#define IDC_COMBO_TEXT_STYLE            1050
#define IDC_BUTTON_LINE_NO_COLOR        1050
#define IDC_RADIO_YAXIS_ALPHABETIC      1050
#define IDC_EDIT_PIPE_EQP_DIST          1050
#define IDC_EDIT_MODEL_OFFSET_X         1050
#define IDC_COMBO_MATCHLINE_DATA_TEXT_STYLE 1050
#define IDC_PROGRESS                    1051
#define IDC_RADIO_COLUMN_NAME_FORMAT1   1051
#define IDC_BUTTON_COORD_COLOR          1051
#define IDC_RADIO_TOP                   1051
#define IDC_EDIT_ELEV_DIST              1051
#define IDC_COMBO_NOZZLE_TEXT_STYLE     1051
#define IDC_EDIT_MODEL_OFFSET_Y         1051
#define IDC_COMBO_TEXT_STYLE2           1051
#define IDC_COMBO_DISPLAY_NAME          1051
#define IDC_RADIO_COLUMN_NAME_FORMAT2   1052
#define IDC_COMBO_ARROW                 1052
#define IDC_RADIO_MIXED                 1052
#define IDC_EDIT_STR_DIST               1052
#define IDC_EDIT_MODEL_OFFSET_Z         1052
#define IDC_BUTTON_VIEW_INFO_COLOR      1052
#define IDC_BUTTON_LINE_COLOR           1053
#define IDC_RADIO_OFF                   1053
#define IDC_COMBO_COORDINATE_TEXT_STYLE 1053
#define IDC_EDIT_DIST_A                 1053
#define IDC_BUTTON_MATCHLINE_DATA_COLOR 1053
#define IDC_BUTTON_TEXT_COLOR           1054
#define IDC_BUTTON_CENTERLINE_COLOR     1054
#define IDC_RADIO12                     1054
#define IDC_EDIT_DIST_B                 1054
#define IDC_RADIO_OUTSIDE_ALIGNMENT     1054
#define IDC_BUTTON_EQP_NAME_COLOR       1055
#define IDC_RADIO13                     1055
#define IDC_EDIT_DIST_C                 1055
#define IDC_RADIO_OVERLAP_ON            1055
#define IDC_RADIO_INSIDE_ALIGNMENT      1055
#define IDC_EDIT_E1                     1056
#define IDC_RADIO_OVERLAP_OFF           1056
#define IDC_BUTTON_SELECT_SERVER        1057
#define IDC_COMBO_EQP_NAME_TEXT_STYLE   1057
#define IDC_EDIT_E2                     1057
#define IDC_RADIO_TAG                   1057
#define IDC_STATIC_MSG                  1058
#define IDC_BUTTON_LEADER_COLOR         1058
#define IDC_EDIT_E3                     1058
#define IDC_EDIT_O1                     1058
#define IDC_RADIO_OVERLAP_OFF2          1058
#define IDC_RADIO_NO_TAG                1058
#define IDC_STATIC_TITLE                1059
#define IDC_BUTTON_LABEL_COLOR          1059
#define IDC_EDIT_INSIDE_PIPE_EQP_DIST   1059
#define IDC_BUTTON_NOZZLE_LABEL_COLOR   1060
#define IDC_BUTTON_CENTER_LINE_COLOR    1060
#define IDC_EDIT_ELEV_DIST2             1060
#define IDC_EDIT_INSIDE_ELEV_DIST       1060
#define IDC_RADIO_COLUMN_DATA           1060
#define IDC_EDIT_DIST_D                 1060
#define IDC_RADIO_UP                    1061
#define IDC_EDIT_DIST_E                 1061
#define IDC_RADIO_DOWN                  1062
#define IDC_RADIO_UP_DOWN               1063
#define IDC_RADIO_LEFT                  1064
#define IDC_CHECK_INST2                 1064
#define IDC_RADIO_RIGHT                 1065
#define IDC_CHECK_FITTING_TYPE2         1065
#define IDC_RADIO_LEFT_RIGHT            1066
#define IDC_EDIT_DELIMITER              1067
#define IDC_EDIT_BUBBLE_SIZE            1068
#define IDC_RADIO_GRID_LINE_DATA        1069
#define IDC_BUTTON_DIM_LINE_COLOR       1070
#define IDC_STATIC_PROJECT              1071
#define IDC_BUTTON_EXT_LINE_COLOR       1071
#define IDC_STATIC_ID                   1072
#define IDC_COMBO_ARROW_TYPE            1072
#define IDC_STATIC_PASSWORD             1073
#define IDC_EDIT_TEXT_OFFSET            1073
#define IDC_COMBO_LEADER_LEVEL          1073
#define IDC_EDIT_DIM_LINE_DISTANCE      1074
#define IDC_COMBO_LEADER_STYLE          1074
#define IDC_EDIT_EXT_LINE_EXTENSION     1075
#define IDC_COMBO_LEADER_WEIGHT         1075
#define IDC_STATIC_PICTURE              1076
#define IDC_COMBO_LABEL_LEVEL           1076
#define IDC_COMBO_CENTER_LINE_LEVEL     1076
#define IDC_BUTTON_LINE_NO_TEXT_COLOR   1077
#define IDC_BUTTON1                     1077
#define IDC_COMBO_LABEL_STYLE           1077
#define IDC_COMBO_NOZZLE_LABEL_LEVEL    1077
#define IDC_BUTTON_NEW_REV_DATA         1077
#define IDC_COMBO_CENTER_LINE_WEIGHT    1077
#define IDC_BUTTON_NEW_ITEM             1077
#define IDC_BUTTON_RESET_ACTIVATE_CODE  1077
#define IDC_BUTTON_ELEV_TEXT_COLOR      1078
#define IDC_COMBO_LABEL_WEIGHT          1078
#define IDC_COMBO_CENTER_LINE_STYLE     1078
#define IDC_BUTTON_NEW_ITEM2            1078
#define IDC_BUTTON_DELETE_ITEM          1078
#define IDC_COMBO_NOZZLE_LABEL_STYLE    1079
#define IDC_RADIO_ON                    1080
#define IDC_COMBO_PF_HATCHING_TEXT_STYLE 1080
#define IDC_BUTTON_ORIGIN_PICK          1080
#define IDC_RADIO_LINE_NO_ONLY          1081
#define IDC_COMBO_PF_HATCHING_TEXT_LEVEL 1081
#define IDC_RADIO_LINE_NO_ELEV          1082
#define IDC_COMBO_PF_HATCHING_LEADER_LEVEL 1082
#define IDC_RADIO_LINE_NO_OVER_ELEV     1083
#define IDC_EDIT_PF_HATCHING_TEXT_OFFSET 1083
#define IDC_STATIC_ENCLOSURE            1084
#define IDC_COMBO_PF_HATCHING_LEVEL     1084
#define IDC_COMBO_ENCLOSURE_TYPE        1085
#define IDC_COMBO_PF_HATCHING_CELL_NAME 1085
#define IDC_BUTTON_LEADER_LINE_COLOR    1086
#define IDC_COMBO_EQP_HATCHING_CELL_NAME 1086
#define IDC_COMBO_PF_HATCHING_STYLE     1086
#define IDC_COMBO2                      1087
#define IDC_COMBO_STR_PF_LEVEL          1087
#define IDC_COMBO_EQP_HATCHING_LEVEL    1087
#define IDC_BUTTON_ENCLOSURE_COLOR      1088
#define IDC_COMBO_PF_HATCHING_WEIGHT    1088
#define IDC_COMBO_EQP_HATCHING_STYLE    1088
#define IDC_STATIC_LABEL                1089
#define IDC_COMBO_TEXT_LEVEL            1089
#define IDC_COMBO_EQP_HATCHING_WEIGHT   1089
#define IDC_COMBO_PF_HATCHING_LEADER_STYLE 1089
#define IDC_COMBO_LABEL_TYPE            1090
#define IDC_EDIT_PF_HATCHING_CELL_LIBRARY 1090
#define IDC_COMBO_EQP_HATCHING_LEVEL2   1090
#define IDC_COMBO_EQP_HATCHING_SCALE    1090
#define IDC_BUTTON_LABEL_TEXT_COLOR     1091
#define IDC_EDIT_EQP_HATCHING_CELL_LIBRARY 1091
#define IDC_COMBO_PF_HATCHING_LEADER_WEIGHT 1091
#define IDC_COMBO3                      1092
#define IDC_EDIT_EQP_HATCHING_OFFSET    1092
#define IDC_COMBO_PF_HATCHING_ARROW_TYPE 1092
#define IDC_STATIC_NOZZLE               1093
#define IDC_COMBO5                      1093
#define IDC_COMBO_EQP_PF_LEVEL          1093
#define IDC_BUTTON_NEW_LEVEL_ITEM       1093
#define IDC_BUTTON_DELETE_LEVEL_ITEM    1094
#define IDC_COMBO_PF_HATCHING_SIZE      1094
#define IDC_STATIC_REDUCER              1095
#define IDC_CHECK_TOP_SIDE              1095
#define IDC_COMBO_EQP_PF_LEVEL2         1095
#define IDC_COMBO_CONCRETE_PF_LEVEL     1095
#define IDC_CHECK_BOTTOM_SIDE           1096
#define IDC_EDIT_PF_HATCHING_ARROW_SIZE 1096
#define IDC_STATIC_LESS_THAN            1097
#define IDC_CHECK_LEFT_SIDE             1097
#define IDC_EDIT_LABEL_OFFSET           1097
#define IDC_STATIC_GREATER_EQUAL        1098
#define IDC_CHECK_RIGHT_SIDE            1098
#define IDC_EDIT_ECC_LABELING           1098
#define IDC_STATIC_EQUIPMENT_HATCHING   1099
#define IDC_EDIT_CON_LABELING           1099
#define IDC_CHECK_SEC_TOP_SIDE          1099
#define IDC_BUTTON_EQUIPMENT_HATCHING_COLOR 1100
#define IDC_RADIO_MAIN_RUN              1100
#define IDC_CHECK_SEC_BOTTOM_SIDE       1100
#define IDC_STATIC_PLATFORM_HATCHING    1101
#define IDC_RADIO_RUN_MAIN              1101
#define IDC_CHECK_SEC_LEFT_SIDE         1101
#define IDC_BUTTON_PLATFORM_HATCHING_COLOR 1102
#define IDC_BUTTON_PF_HATCHING_TEXT_COLOR 1102
#define IDC_RADIO_METRIC                1102
#define IDC_CHECK_SEC_RIGHT_SIDE        1102
#define IDC_CHECK_DEPEND_ON_SIZE        1103
#define IDC_BUTTON_FLOW_MARK_COLOR      1103
#define IDC_BUTTON_PF_HATCHING_LEADER_COLOR 1103
#define IDC_RADIO_INCH                  1103
#define IDC_COMBO_LESS_THAN             1104
#define IDC_BUTTON_SLOPE_MARK_TEXT_COLOR 1104
#define IDC_STATIC_REV_CHART            1104
#define IDC_STATIC_FLOW_MARK            1105
#define IDC_BUTTON_PF_HATCHING_COLOR    1105
#define IDC_EDIT_REV_CHART_ROW_COUNT    1105
#define IDC_EDIT_OFFSET_A               1106
#define IDC_STATIC_REV_CHART_INFO       1106
#define IDC_STATIC_NOZZLE_CHART         1106
#define IDC_EDIT_OFFSET_B               1107
#define IDC_STATIC_NOZZLE_CHART_INFO    1107
#define IDC_EDIT_REV_CHART_ROW_HEIGHT   1107
#define IDC_COMBO_SIZE                  1108
#define IDC_STATIC_SLOPE_MARK           1108
#define IDC_BUTTON_MOVE_NEXT            1108
#define IDC_STATIC_LESS_THAN_LABEL      1109
#define IDC_EDIT_OFFSET_A2              1109
#define IDC_EDIT_NOZZLE_CHART_ROW_COUNT 1109
#define IDC_STATIC_LINE_NO_1            1110
#define IDC_STATIC_GREATER_EQUAL_LABEL  1110
#define IDC_RADIO_GRID_NO_ON            1110
#define IDC_STATIC_LINE_NO_2            1111
#define IDC_RADIO_GRID_NO_OFF           1111
#define IDC_STATIC_ELEV_1               1112
#define IDC_EDIT_ORIGIN_X               1112
#define IDC_STATIC_ELEV_2               1113
#define IDC_EDIT_ORIGIN_Y               1113
#define IDC_RADIO_ELEV                  1114
#define IDC_RADIO_ORIGIN_1              1114
#define IDC_RADIO_ELEV_COORD            1115
#define IDC_RADIO_ORIGIN_2              1115
#define IDC_RADIO_ONLY_LINE_NO          1116
#define IDC_RADIO_ORIGIN_3              1116
#define IDC_EDIT_BORDER_FILE_NAME       1117
#define IDC_RADIO_ORIGIN_4              1117
#define IDC_EDIT_BORDER_DESC            1118
#define IDC_COMBO_EQP_TEXT_STYLE        1118
#define IDC_COMBO_PAPER_SIZE            1119
#define IDC_COMBO_EQP_LABEL_LEVEL       1119
#define IDC_EDIT_KEY_PLAN_FILE          1120
#define IDC_BUTTON_EQP_LABEL_COLOR      1120
#define IDC_EDIT_KEY_PLAN_X             1121
#define IDC_COMBO_EQP_LABEL_STYLE       1121
#define IDC_EDIT_KEY_PLAN_Y             1122
#define IDC_EDIT_EQP_ROW_HEIGHT         1122
#define IDC_RADIO_DISPLAY_STYLE1        1122
#define IDC_BUTTON_KEY_PLAN_PICK        1123
#define IDC_EDIT_NOZZLE_ROW_HEIGHT      1123
#define IDC_LIST_REVISION_DATA          1123
#define IDC_EDIT_ENCLOSURE_A            1124
#define IDC_EDIT_KEY_PLAN_FILE4         1124
#define IDC_BUTTON_DELETE_REV_DATA      1124
#define IDC_EDIT_KEY_PLAN_SCALE         1124
#define IDC_EDIT_ENCLOSURE_B            1125
#define IDC_EDIT_NORTH_MARK_FILE        1125
#define IDC_EDIT_NO                     1125
#define IDC_COMBO_LEADER_ARROW_TYPE     1126
#define IDC_EDIT_NORTH_MARK_X           1126
#define IDC_EDIT_DATE                   1126
#define IDC_RADIO_ALL_SYMBOL_LINE       1126
#define IDC_EDIT_LEADER_ARROW_SIZE      1127
#define IDC_EDIT_NORTH_MARK_Y           1127
#define IDC_EDIT_DESC                   1127
#define IDC_RADIO_ALL_AS_IT_WAS         1127
#define IDC_EDIT_LABEL_DELIMITER        1128
#define IDC_BUTTON_NORTH_MARK_PICK      1128
#define IDC_EDIT_DRAWN_BY               1128
#define IDC_RADIO_DEPEND_ON_SIZE        1128
#define IDC_COMBO_LABEL_TEXT_STYLE      1129
#define IDC_EDIT_KEY_PLAN_FILE8         1129
#define IDC_EDIT_CHECKED_BY             1129
#define IDC_COMBO_PIPE_SIZE             1129
#define IDC_EDIT_NORTH_MARK_SCALE       1129
#define IDC_EDIT_SCALE_BAR_FILE         1130
#define IDC_EDIT_REVIEWED_BY            1130
#define IDC_STATIC_LINE_PROPERTY        1130
#define IDC_EDIT_SCALE_BAR_X            1131
#define IDC_EDIT_APPROVED_BY            1131
#define IDC_EDIT_SDR_NAME               1131
#define IDC_EDIT_SCALE_BAR_Y            1132
#define IDC_CHECK_VIEW_LINE             1132
#define IDC_EDIT_APPROVED_BY2           1132
#define IDC_EDIT_REV_H                  1132
#define IDC_BUTTON_SCALE_BAR_PICK       1133
#define IDC_COMBO_LINE_NO_LEVEL         1133
#define IDC_CHECK_VIEW_LINE2            1133
#define IDC_CHECK_HIDDEN_LINE           1133
#define IDC_EDIT_SCALE_BAR_SCALE        1134
#define IDC_COMBO_LINE_NO_STYLE         1134
#define IDC_EDIT_SCALE_VALUE            1135
#define IDC_BUTTON_ELEV_COLOR           1135
#define IDC_STATIC_denominator          1136
#define IDC_COMBO_ELEV_LEVEL            1136
#define IDC_STATIC_X                    1137
#define IDC_COMBO_ELEV_STYLE            1137
#define IDC_STATIC_Y                    1138
#define IDC_COMBO_ELEV_STYLE2           1138
#define IDC_COMBO_GROUPING_LEVEL        1138
#define IDC_STATIC_SCALE                1139
#define IDC_STATIC_TITLE_BLOCK          1140
#define IDC_COMBO_KEY_PLAN_CELL_NAME    1140
#define IDC_BUTTON_NEW_TITLE_BLOCK_ITEM 1141
#define IDC_COMBO_NAME_TEXT_STYLE       1141
#define IDC_COMBO_PAPER_SIZE3           1141
#define IDC_COMBO_NORTH_MARK_CELL_NAME  1141
#define IDC_BUTTON_DELETE_TITLE_BLOCK_ITEM 1142
#define IDC_COMBO_NAME_LEVEL            1142
#define IDC_BUTTON_OPEN_BORDER_FILE     1142
#define IDC_EDIT_TITLE_BLOCK_ITEM       1143
#define IDC_BUTTON_NAME_COLOR           1143
#define IDC_STATIC_GRID_NO              1144
#define IDC_COMBO_NAME_STYLE            1144
#define IDC_BUTTON_BASE_POSITION        1145
#define IDC_COMBO_COORD_LEVEL           1145
#define IDC_CHECK1                      1146
#define IDC_BUTTON_X_AXIS_DISTANCE      1146
#define IDC_CHECK_INSULATION_LEVEL_DISPLAY 1146
#define IDC_COMBO_OUTSIDE_EQP_DISPLAY_STYLE 1146
#define IDC_COMBO_VIEW_INFO_LEVEL       1146
#define IDC_CHECK_SKIP_EQP_HAS_NO_NOZZLE 1146
#define IDC_CHECK_TRIM_END              1146
#define IDC_BUTTON_Y_AXIS_DISTANCE      1147
#define IDC_EDIT_THIS_DRAWING_TEXT      1147
#define IDC_COMBO_COORD_STYLE           1147
#define IDC_STATIC_KEY_PLAN_HATCHING    1148
#define IDC_RADIO_INSIDE_VIEW           1148
#define IDC_COMBO_VIEW_INFO_STYLE       1148
#define IDC_STATIC_THIS_DRAWING_TEXT    1149
#define IDC_RADIO_OUTSIDE_VIEW          1149
#define IDC_COMBO_MATCHLINE_DATA_LEVEL  1149
#define IDC_COMBO_KEY_PLAN_ANGLE        1150
#define IDC_CHECK_COORD_DISPLAY         1150
#define IDC_COMBO_KEYPLAN_HATCHING_ANGLE 1150
#define IDC_COMBO_MATCHLINE_DATA_STYLE  1150
#define IDC_CHECK_CENTER_LINE_DISPLAY   1151
#define IDC_CHECK_LEADER_DISPLAY        1151
#define IDC_EDIT_LINE_NO_LABEL          1152
#define IDC_COMBO_LINE_LEVEL            1152
#define IDC_COMBO_LINE_STYLE            1153
#define IDC_BUTTON_ELEVATION_TYPE_BY_SPEC 1153
#define IDC_COMBO_DELIMITER             1154
#define IDC_COMBO_LINE_WEIGHT           1154
#define IDC_BUTTON_ADD                  1155
#define IDC_STATIC_SQL_SERVER           1155
#define IDC_COMBO_LINE_LEVEL2           1155
#define IDC_COMBO_GRID_CIRCLE_LEVEL     1155
#define IDC_LISTBUDDY                   1156
#define IDC_EDIT_PROJECT_DATABASE_NAME  1156
#define IDC_EDIT_HOST                   1156
#define IDC_LIST_LINE_NO_LABEL_ITEM     1157
#define IDC_EDIT_PROJECT_USER_ID        1157
#define IDC_EDIT_PROJECT_PASSWORD       1158
#define IDC_EDIT_PROJECT_SERVER         1159
#define IDC_EDIT_SERVICE                1159
#define IDC_EDIT_EQP_DDL_FILE_PATH      1160
#define IDC_EDIT_DESIGN_USER_ID         1160
#define IDC_EDIT_DESIGN_DDL_FILE_PATH   1161
#define IDC_EDIT_IMPORT_HIDDEN_LEVEL    1161
#define IDC_EDIT_PROJECT_PASSWORD2      1161
#define IDC_EDIT_PIPE_FOLDER            1162
#define IDC_RADIO_ORACLE                1162
#define IDC_RADIO_GENERATE              1162
#define IDC_EDIT_INSULATION_LEVEL       1162
#define IDC_EDIT_EQUIPMENT_FOLDER       1163
#define IDC_RADIO_SQL_SERVER            1163
#define IDC_RADIO_IMPORT                1163
#define IDC_EDIT_TITLE_BLOCK_ITEM_LABEL 1163
#define IDC_EDIT_WELD_MARK_SIZE         1163
#define IDC_RADIO_ACCESS                1164
#define IDC_EDIT_STRUCTURE_FOLDER       1164
#define IDC_CHECK_DISPLAY_LEADER_LINE   1164
#define IDC_EDIT_WELD_MARK_SIZE2        1164
#define IDC_EDIT_FIXED_SIZE             1164
#define IDC_RADIO_WINDOWS_USER          1165
#define IDC_EDIT_CABLE_TRAY_FOLDER      1165
#define IDC_COMBO_VERTICAL_PIPE_HATCHING_LEVEL 1165
#define IDC_RADIO_SQL_SERVER_USER       1166
#define IDC_EDIT_MISC_FOLDER            1166
#define IDC_BUTTON_VERTICAL_PIPE_HATCHING_COLOR 1166
#define IDC_BUTTON_TEST_PROJECT_DATBASE_CONNECTION 1167
#define IDC_EDIT_DRAWING_FOLDER         1167
#define IDC_COMBO_VERTICAL_PIPE_HATCHING_STYLE 1167
#define IDC_BUTTON_TEST_DESIGN_DATABASE_CONNECTION 1168
#define IDC_COMBO_VERTICAL_PIPE_HATCHING_WEIGHT 1168
#define IDC_EDIT_ACCESS_FILE_PATH       1169
#define IDC_STATIC_VERSION              1169
#define IDC_BUTTON_DATABASE_DUMP        1170
#define IDC_BUTTON_MOVE_PREV            1170
#define IDC_STATIC_GROUP_BOX            1171
#define IDC_CTRL_PROGRESS               1171
#define IDC_RADIO_UPPER_LEFT            1172
#define IDC_EDIT_KEYPLAN_HATCHING_MODEL_X 1172
#define IDC_RADIO_DRV_FILE              1172
#define IDC_RADIO_UPPER_RIGHT           1173
#define IDC_EDIT_KEYPLAN_HATCHING_MODEL_Y 1173
#define IDC_RADIO_LOWER_LEFT            1174
#define IDC_EDIT_KEYPLAN_HATCHING_X_SCALE 1174
#define IDC_RADIO_LOWER_RIGHT           1175
#define IDC_EDIT_KEYPLAN_HATCHING_Y_SCALE 1175
#define IDC_EDIT_X                      1176
#define IDC_COMBO_KEYPLAN_HATCHING_TEXT_STYLE 1176
#define IDC_EDIT_Y                      1177
#define IDC_EDIT_BORDER_SCALE           1177
#define IDC_RADIO_XAXIS_NUMERIC         1178
#define IDC_COMBO_KEYPLAN_NAME_LEVEL    1178
#define IDC_RADIO_XAXIS_ALPHABETIC      1179
#define IDC_BUTTON_KEYPLAN_NAME_COLOR   1179
#define IDC_EDIT_XAXIS_DIST             1180
#define IDC_EDIT_YAXIS_DIST             1181
#define IDC_MYPICTURE                   1182
#define IDC_STATIC_VIEW_ANNO            1183
#define IDC_CHECK_VIEW_COORD_BOX_DISPLAY 1184
#define IDC_EDIT_VIEW_INFO_DIST         1185
#define IDC_EDIT_MATCHLINE_DATA_DIST    1186
#define IDC_COMBO_VIEW_COORD_TEXT_STYLE 1187
#define IDC_COMBO_VIEW_COORD_LEVEL      1188
#define IDC_BUTTON_VIEW_COORD_COLOR     1189
#define IDC_COMBO_VIEW_COORD_STYLE      1190
#define IDC_CHECK_AUTO_SIZE             1191
#define IDC_RADIO_AUTO                  1192
#define IDC_RADIO_AUTO2                 1193
#define IDC_RADIO_SELECT                1193
#define IDC_STATIC_REV_DATA_INFO        1193
#define IDC_RADIO_ONLY_NAME             1194
#define IDC_RADIO_NAME_ELEV             1195
#define IDC_RADIO_ENCLOUSER_NONE        1196
#define IDC_RADIO_ENCLOSURE_NONE        1196
#define IDC_BUTTON_THIS_DRAWING_PICK    1196
#define IDC_RADIO_ENCLOSURE_RECTANGLE   1197
#define IDC_EDIT_CAD_APPLICATION        1197
#define IDC_STATIC_TAB_CTRL             1198
#define IDC_BUTTON_NEW_PIPE_DIA_DATA    1199
#define IDC_BUTTON_DELETE_PIPE_DIA_DATA 1200
#define IDC_STATIC_GRID_CTRL            1201
#define IDC_RADIO_EQUAL_OD              1202
#define IDC_RADIO_FIXED_SIZE            1203
#define IDC_STATIC_ANNO_FILTER          1206
#define IDC_STATIC_MATCHLINE_DRAWING_PREFIX 1207
#define IDC_COMBO_LINE_NO_TEXT_STYLE    3049
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_PROJECT_NEW                  32771
#define ID_PROJECT_DELETE               32772
#define ID__COPYEDIT                    32773
#define ID_DRA_COPYEDIT                 32774
#define ID__DELETE                      32775
#define ID_DRA_DELETE                   32776
#define ID__EDIT                        32777
#define ID_DRA_EDIT                     32778
#define ID_DRA_NEW                      32779
#define ID_VIEW_NEW                     32780
#define ID_VIEW_COPYEDIT                32781
#define ID__UPDATE_BORDER_SETTING_DATA  32781
#define ID_VIEW_DELETE                  32782
#define ID_BORDER_OPEN                  32783
#define ID_DRA_OPEN                     32784
#define ID_PROJECT_EDIT                 32785
#define ID_DRA_EDIT_TITLE_BLOCK_DATA    32787
#define ID_EDIT_ELEVATION_TYPE_BY_SPEC  32788
#define ID_EDIT_TITLE_BLOCK_DATA        32788
#define ID_OUTPUT_DELETE                32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        459
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1208
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
