/*----------------------------------------------------------------------+
|									|
|  Copyright (1995) Bentley Systems, Inc., All rights reserved.		|
|									|
|  "MicroStation" is a registered trademark and "MDL" and "MicroCSL"	|
|  are trademarks of Bentley Systems, Inc.			    	|
|									|
|  Limited permission is hereby granted to reproduce and modify this	|
|  copyrighted material provided that the resulting code is used only 	|
|  in conjunction with Bentley Systems products under the terms of the	|
|  license agreement provided therein, and that this notice is retained	|
|  in its entirety in any such reproduction or modification.		|
|									|
+----------------------------------------------------------------------*/
/*----------------------------------------------------------------------+
|									|
|    $Logfile:   J:/mdl/examples/cellpick/english/cellptxt.h_v  $
|   $Workfile:   cellptxt.h  $
|   $Revision: 1.1 $
|   	$Date: 2010/12/16 09:07:01 $
|									|
+----------------------------------------------------------------------*/
/*----------------------------------------------------------------------+
|									|
|   Function -								|
|									|
|	Static dialog box text						|
|									|
+----------------------------------------------------------------------*/
#if !defined (__cellptxtH__)
#define	__cellptxtH__

#define	TXT_CellPicker			    "Cell Picker"

#endif /* if !defined (__cellptxtH__) */
